{
  "openapi": "3.0.3",
  "info": {
    "title": "ConnectWise Asio APIs",
    "description": "ConnectWise Asio",
    "version": "1.0"
  },
  "servers": [
    {
      "url": "https://openapi.service.itsupport247.net"
    }
  ],
  "paths": {
    "/api/platform/v1/device-groups": {
      "get": {
        "tags": [
          "Device Groups"
        ],
        "summary": "Fetch all Device Groups",
        "operationId": "Get_details_of_Devices_Groups",
        "security": [
          {
            "device_groups": [
              "platform.deviceGroups.read"
            ]
          }
        ]
      }
    },
    "/api/platform/v1/automation/shellScripts": {
      "get": {
        "tags": [
          "Automation"
        ],
        "summary": "Fetch all Shell Scripts",
        "operationId": "Get_details_of_Shell_Scripts",
        "security": [
          {
            "automation_read": [
              "platform.automation.read"
            ]
          }
        ]
      }
    },
    "/api/platform/v1/automation/scripts": {
      "get": {
        "tags": [
          "Automation"
        ],
        "summary": "Fetch all Scripts",
        "operationId": "Get_details_of_Scripts",
        "security": [
          {
            "automation_read": [
              "platform.automation.read"
            ]
          }
        ]
      }
    },
    "/api/platform/v1/automation/tasks": {
      "get": {
        "tags": [
          "Automation"
        ],
        "summary": "Fetch all Tasks",
        "operationId": "Get_details_of_Tasks",
        "security": [
          {
            "automation_read": [
              "platform.automation.read"
            ]
          }
        ]
      }
    },
    "/v1/token": {
      "post": {
        "tags": [
          "Authorization"
        ],
        "summary": "Authorize with credentials",
        "operationId": "Authorize_with_credentials"
      }
    },
    "/v1/rate_limits": {
      "get": {
        "tags": [
          "Rate Limits"
        ],
        "summary": "Get current rate limit",
        "operationId": "Get_current_rate_limit",
        "security": [
          {
            "openapi_oauth": []
          }
        ]
      }
    },
    "/api/platform/v1/company/companies": {
      "get": {
        "tags": [
          "Company"
        ],
        "summary": "Get list for companies",
        "operationId": "Get_list_for_companies",
        "security": [
          {
            "platform": [
              "platform.companies.read"
            ]
          }
        ]
      }
    },
    "/api/platform/v1/company/companies/{companyId}": {
      "get": {
        "tags": [
          "Company"
        ],
        "summary": "Get a company by id",
        "operationId": "Get_a_company_by_id",
        "security": [
          {
            "platform": [
              "platform.companies.read"
            ]
          }
        ]
      }
    },
    "/api/platform/v1/company/companies/{companyId}/sites": {
      "get": {
        "tags": [
          "Company"
        ],
        "summary": "Get all sites for the company",
        "operationId": "Get_all_sites_for_the_company",
        "security": [
          {
            "platform": [
              "platform.sites.read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Company"
        ],
        "summary": "Create a site for the company",
        "operationId": "Create_a_site_for_the_company",
        "security": [
          {
            "platform": [
              "platform.sites.write"
            ]
          }
        ]
      }
    },
    "/api/platform/v1/company/companies/{companyId}/sites/{siteId}": {
      "get": {
        "tags": [
          "Company"
        ],
        "summary": "Get site by id for company",
        "operationId": "Get_site_by_id_for_company",
        "security": [
          {
            "platform": [
              "platform.sites.read"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Company"
        ],
        "summary": "Update site by id for company",
        "operationId": "Update_site_by_id_for_company",
        "security": [
          {
            "platform": [
              "platform.sites.write"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Company"
        ],
        "summary": "Update site by id for company",
        "operationId": "Update_site_by_id_for_company_2",
        "security": [
          {
            "platform": [
              "platform.sites.write"
            ]
          }
        ]
      }
    },
    "/api/platform/v1/company/sites": {
      "get": {
        "tags": [
          "Company"
        ],
        "summary": "Get list for sites",
        "operationId": "Get_list_for_sites",
        "security": [
          {
            "platform": [
              "platform.sites.read"
            ]
          }
        ]
      }
    },
    "/api/platform/v1/company/sites/{siteId}": {
      "get": {
        "tags": [
          "Company"
        ],
        "summary": "Get site by id",
        "operationId": "Get_site_by_id",
        "security": [
          {
            "platform": [
              "platform.sites.read"
            ]
          }
        ]
      }
    },
    "/api/platform/v1/device/endpoints": {
      "get": {
        "tags": [
          "Devices"
        ],
        "summary": "Get details of Devices for a partner",
        "operationId": "Get_details_of_Devices_for_a_partner",
        "security": [
          {
            "endpoints_list": [
              "platform.asset.read"
            ]
          }
        ]
      }
    },
    "/api/platform/v1/device/clients/{clientID}/endpoints": {
      "get": {
        "tags": [
          "Devices"
        ],
        "summary": "Get details of Devices for a specific company",
        "operationId": "Get_details_of_Devices_for_a_specific_company",
        "security": [
          {
            "endpoints_list": [
              "platform.asset.read"
            ]
          }
        ]
      }
    },
    "/api/platform/v1/device/clients/{clientID}/sites/{siteID}/endpoints": {
      "get": {
        "tags": [
          "Devices"
        ],
        "summary": "Get details of Devices for a specific site",
        "operationId": "Get_details_of_Devices_for_a_specific_site",
        "security": [
          {
            "endpoints_list": [
              "platform.asset.read"
            ]
          }
        ]
      }
    },
    "/api/platform/v1/device/endpoints/{endpointID}": {
      "get": {
        "tags": [
          "Devices"
        ],
        "summary": "Get details of a specific Device",
        "operationId": "Get_details_of_a_specific_Device",
        "security": [
          {
            "endpoints_list": [
              "platform.asset.read"
            ]
          }
        ]
      }
    },
    "/api/platform/v1/service/ticketing/categories": {
      "get": {
        "tags": [
          "Tickets"
        ],
        "summary": "Returns all ticket categories for a partner",
        "description": "This API returns all the ticket categories for a partner. Pagination support is not available for this API yet, so this API may return large amount of data depending upon categories present for a partner in the system.\n",
        "operationId": "get__api_platform_v1_service_ticketing_categories"
      }
    },
    "/api/platform/v1/service/ticketing/priorities": {
      "get": {
        "tags": [
          "Tickets"
        ],
        "summary": "Returns all ticket priorities",
        "description": "This API returns all the available priorities in the system. Pagination support is not available for this API yet, so this API may return large amount of data depending upon priorities present in the system.\n",
        "operationId": "get__api_platform_v1_service_ticketing_priorities"
      }
    },
    "/api/platform/v1/service/ticketing/service-boards": {
      "get": {
        "tags": [
          "Tickets"
        ],
        "summary": "Returns all service-boards for provided partner, available in the service",
        "description": "This API returns all the available service-boards in the system, for partner with provided partnerId. Pagination support is not available for this API yet, so this API may return large amount of data depending upon serviceBoards present in the system.\n\nThe API accepts query parameters which should be provided to identify available service boards to assigns tickets to. \nAs the CW Expert Service only support entitled companies and sites, providing companyId and siteId al[...]",
        "operationId": "get__api_platform_v1_service_ticketing_service_boards"
      }
    },
    "/api/platform/v1/service/ticketing/service-boards/{id}/teams": {
      "get": {
        "tags": [
          "Tickets"
        ],
        "summary": "Returns all team associations for a service-board",
        "description": "This API fetches all the team associations for a specific service-board.\n",
        "operationId": "get__api_platform_v1_service_ticketing_service_boards__id__teams"
      }
    },
    "/api/platform/v1/service/ticketing/sources": {
      "get": {
        "tags": [
          "Tickets"
        ],
        "summary": "Returns all ticket sources for a partner",
        "description": "This API returns all the ticket sources for a partner. Pagination support is not available for this API yet, so this API may return large amount of data depending upon sources present for a partner in the system.\n",
        "operationId": "get__api_platform_v1_service_ticketing_sources"
      }
    },
    "/api/platform/v1/service/ticketing/statuses": {
      "get": {
        "tags": [
          "Tickets"
        ],
        "summary": "Returns all ticket statuses",
        "description": "This API returns all the available statuses in the system. Pagination support is not available for this API yet, so this API may return large amount of data depending upon statuses present in the system.\n",
        "operationId": "get__api_platform_v1_service_ticketing_statuses"
      }
    },
    "/api/platform/v1/service/ticketing/tags": {
      "get": {
        "tags": [
          "Tickets"
        ],
        "summary": "Returns all tags for provided partner, available in the service",
        "description": "This API returns all the available tags in the system, for partner with provided partnerId. Pagination support is not available for this API yet, so this API may return large amount of data depending upon tags present in the system.\n",
        "operationId": "get__api_platform_v1_service_ticketing_tags"
      },
      "post": {
        "tags": [
          "Tickets"
        ],
        "summary": "Creates a new tag",
        "description": "This API creates a new tag in the system. The 'id' parameter value in the request body is ignored, if provided. A new 'id' is created  for the newly created tag and provided in response body\n",
        "operationId": "post__api_platform_v1_service_ticketing_tags"
      }
    },
    "/api/platform/v1/service/ticketing/tags/{id}": {
      "delete": {
        "tags": [
          "Tickets"
        ],
        "summary": "Deletes a tag",
        "description": "The API deletes the stored tag from system.\n",
        "operationId": "delete__api_platform_v1_service_ticketing_tags__id_"
      },
      "get": {
        "tags": [
          "Tickets"
        ],
        "summary": "Returns a tag",
        "description": "Fetches the tag stored in the system against the provided id.\n",
        "operationId": "get__api_platform_v1_service_ticketing_tags__id_"
      },
      "patch": {
        "tags": [
          "Tickets"
        ],
        "summary": "Updates a tag",
        "description": "This API updates the existing tag based on JSON Patch request received. This API is suitable for changing specific fields of the tag without replacing the entire tag object. For more details on JSON Patch, please check http://jsonpatch.com/ The 'id' parameter value in the request body is ignored, if sent and 'id' parameter value from path is used as tag id for this API\n",
        "operationId": "patch__api_platform_v1_service_ticketing_tags__id_"
      },
      "put": {
        "tags": [
          "Tickets"
        ],
        "summary": "Replace a tag",
        "description": "This API replaces the existing tag matching provided id with the one provided in the request body. All the tag parameter values, except for 'id', are replaced with their correspoding values from request body of this API call. If certain parameter is absent in the request body, it's default value is used, if possible. The 'id' parameter value in the request body is ignored, if sent and 'id' parameter value from path is used as tag id for this API\n",
        "operationId": "put__api_platform_v1_service_ticketing_tags__id_"
      }
    },
    "/api/platform/v1/service/ticketing/ticket-counts": {
      "get": {
        "tags": [
          "Tickets"
        ],
        "summary": "Returns ticket counts",
        "description": "This API returns ticket counts\n",
        "operationId": "get__api_platform_v1_service_ticketing_ticket_counts"
      }
    },
    "/api/platform/v1/service/ticketing/tickets": {
      "get": {
        "tags": [
          "Tickets"
        ],
        "summary": "Returns selected Service tickets",
        "description": "This API returns selected tickets in the service. Pagination and filtering support is available, see details below.\n\nFor support for Filtering, please note below strategy. \nIn general, you can add as many filter criteria as required by adding those many query parameters. Each query parameter becomes one filter criterion \nand these are ultimately *AND*ed together (tickets matching all criteria are filtered). \nHowever there is a concept of group of criteria. Each filte[...]",
        "operationId": "get__api_platform_v1_service_ticketing_tickets"
      },
      "post": {
        "tags": [
          "Tickets"
        ],
        "summary": "Creates a new Service ticket",
        "description": "This API creates a new ticket in the system.\nThe 'read-only' parameters in the request body are ignored, if provided. See request body schema for details.\n",
        "operationId": "post__api_platform_v1_service_ticketing_tickets"
      }
    },
    "/api/platform/v1/service/ticketing/tickets/{id}": {
      "get": {
        "tags": [
          "Tickets"
        ],
        "summary": "Returns a Service ticket",
        "description": "Fetches the ticket stored in the system against the provided id.\n",
        "operationId": "get__api_platform_v1_service_ticketing_tickets__id_"
      },
      "patch": {
        "tags": [
          "Tickets"
        ],
        "summary": "Updates a Service ticket",
        "description": "This API updates the existing ticket based on JSON Patch request received.\nThis API is suitable for changing specific fields of ticket without replacing the entire ticket object.\nFor more details on JSON Patch, please check http://jsonpatch.com/\nThe 'read-only' fields of ticket body cannot be updated using this API. For getting 'read-only' fields info, see ticket\nschema details\n",
        "operationId": "patch__api_platform_v1_service_ticketing_tickets__id_"
      },
      "put": {
        "tags": [
          "Tickets"
        ],
        "summary": "Replace a Service ticket",
        "description": "This API replaces the existing ticket matching provided number with the one provided in the request body.\nThe ticket parameter values, except for 'read-only' ones (see request body documentation), are replaced with their correspoding values\nfrom request body of this API call.\nIf certain parameter is absent in the request body, it's default value may be used (if available).\n",
        "operationId": "put__api_platform_v1_service_ticketing_tickets__id_"
      }
    },
    "/api/platform/v1/service/ticketing/tickets/{id}/notes": {
      "get": {
        "tags": [
          "Tickets"
        ],
        "summary": "Returns selected Notes for Service ticket",
        "description": "This API fetches the selected notes for a specific ticket from system and returns it.\n",
        "operationId": "get__api_platform_v1_service_ticketing_tickets__id__notes"
      },
      "post": {
        "tags": [
          "Tickets"
        ],
        "summary": "Creates a new Note for a Service ticket",
        "description": "This API creates a new note for the specified ticket in the system. The 'id' parameter value in the request body is ignored, if provided. A new 'id' is created  for the newly created note and provided in response body\n",
        "operationId": "post__api_platform_v1_service_ticketing_tickets__id__notes"
      }
    },
    "/api/platform/v1/service/ticketing/tickets/{id}/notes/{noteId}": {
      "get": {
        "tags": [
          "Tickets"
        ],
        "summary": "Returns a Note for a Service ticket",
        "description": "Fetches the ticket note stored in the system against the provided id.\n",
        "operationId": "get__api_platform_v1_service_ticketing_tickets__id__notes__noteId_"
      },
      "patch": {
        "tags": [
          "Tickets"
        ],
        "summary": "Updates a Note for a Service ticket",
        "description": "This API updates the existing note based on JSON Patch request received. This API is suitable for changing specific fields of note without replacing the entire note object. For more details on JSON Patch, please check http://jsonpatch.com/ The 'id' parameter value in the request body is ignored, if sent and 'id' parameter value from path is used as note id for this API\n",
        "operationId": "patch__api_platform_v1_service_ticketing_tickets__id__notes__noteId_"
      },
      "put": {
        "tags": [
          "Tickets"
        ],
        "summary": "Replace a Note for a Service ticket",
        "description": "This API replaces the existing ticket note matching provided id with the one provided in the request body. All the note parameter values, except for 'id', are replaced with their correspoding values from request body of this API call. If certain parameter is absent in the request body, it's default value is used. The 'id' parameter value in the request body is ignored, if sent and 'id' parameter value from path is used as note id for this API\n",
        "operationId": "put__api_platform_v1_service_ticketing_tickets__id__notes__noteId_"
      }
    },
    "/api/platform/v1/service/ticketing/types": {
      "get": {
        "tags": [
          "Tickets"
        ],
        "summary": "Returns all ticket types",
        "description": "This API returns all the available types in the system. Pagination support is not available for this API yet, so this API may return large amount of data depending upon types present in the system.\n",
        "operationId": "get__api_platform_v1_service_ticketing_types"
      }
    },
    "/v1/custom-field/definitions": {
      "get": {
        "security": [
          {
            "custom_fields": [
              "platform.custom_fields_definitions.read"
            ]
          }
        ],
        "tags": [
          "Custom Fields Definitions"
        ],
        "summary": "Get the list of custom fields definitions for the given partner, including the vendor provided and partner defined.",
        "operationId": "get__v1_custom_field_definitions"
      },
      "post": {
        "security": [
          {
            "custom_fields": [
              "platform.custom_fields_definitions.write"
            ]
          }
        ],
        "tags": [
          "Custom Fields Definitions"
        ],
        "summary": "Create a new custom fields definition schema",
        "operationId": "post__v1_custom_field_definitions"
      }
    },
    "/v1/custom-field/definitions/{definitionID}": {
      "get": {
        "security": [
          {
            "custom_fields": [
              "platform.custom_fields_definitions.read"
            ]
          }
        ],
        "tags": [
          "Custom Fields Definitions"
        ],
        "summary": "Get the schema for the definition by the given definition id",
        "operationId": "get__v1_custom_field_definitions__definitionID_"
      },
      "put": {
        "security": [
          {
            "custom_fields": [
              "platform.custom_fields_definitions.write"
            ]
          }
        ],
        "tags": [
          "Custom Fields Definitions"
        ],
        "summary": "Update the schema for the definition by the given definition id",
        "operationId": "put__v1_custom_field_definitions__definitionID_"
      },
      "delete": {
        "security": [
          {
            "custom_fields": [
              "platform.custom_fields_definitions.write"
            ]
          }
        ],
        "tags": [
          "Custom Fields Definitions"
        ],
        "summary": "Delete definition and all its values by given id",
        "operationId": "delete__v1_custom_field_definitions__definitionID_"
      }
    },
    "/v1/device/endpoints/{endpointID}/custom-fields": {
      "get": {
        "security": [
          {
            "custom_fields": [
              "platform.custom_fields_values.read"
            ]
          }
        ],
        "tags": [
          "Custom Fields Values"
        ],
        "summary": "Retrieve multiple values of custom fields for the specific endpoint",
        "operationId": "get__v1_device_endpoints__endpointID__custom_fields"
      },
      "put": {
        "security": [
          {
            "custom_fields": [
              "platform.custom_fields_values.write"
            ]
          }
        ],
        "tags": [
          "Custom Fields Values"
        ],
        "summary": "Updates multiple custom fields values for the given endpoint",
        "operationId": "put__v1_device_endpoints__endpointID__custom_fields"
      }
    },
    "/v1/company/companies/{companyId}/custom-fields": {
      "get": {
        "security": [
          {
            "custom_fields": [
              "platform.custom_fields_values.read"
            ]
          }
        ],
        "tags": [
          "Custom Fields Values"
        ],
        "summary": "Retrieve multiple values of custom fields for the specific company",
        "operationId": "get__v1_company_companies__companyId__custom_fields"
      },
      "put": {
        "security": [
          {
            "custom_fields": [
              "platform.custom_fields_values.write"
            ]
          }
        ],
        "tags": [
          "Custom Fields Values"
        ],
        "summary": "Updates multiple custom fields values for the given company",
        "operationId": "put__v1_company_companies__companyId__custom_fields"
      }
    },
    "/v1/company/sites/{siteId}/custom-fields": {
      "get": {
        "security": [
          {
            "custom_fields": [
              "platform.custom_fields_values.read"
            ]
          }
        ],
        "tags": [
          "Custom Fields Values"
        ],
        "summary": "Retrieve multiple values of custom fields for the specific site",
        "operationId": "get__v1_company_sites__siteId__custom_fields"
      },
      "put": {
        "security": [
          {
            "custom_fields": [
              "platform.custom_fields_values.write"
            ]
          }
        ],
        "tags": [
          "Custom Fields Values"
        ],
        "summary": "Updates multiple custom fields values for the given site",
        "operationId": "put__v1_company_sites__siteId__custom_fields"
      }
    },
    "/v1/partners/{partnerID}/endpoints/{endpointId}/patches": {
      "get": {
        "tags": [
          "OS Patching"
        ],
        "summary": "Get list of patches by endpoint.",
        "x-cw-openapi": {
          "api-path": "/v1/patching/{endpointID}/patches",
          "api-scopes": [
            "platform.patching.read"
          ]
        },
        "operationId": "get__v1_partners__partnerID__endpoints__endpointId__patches"
      }
    },
    "/api/platform/v1/automation/endpoints/schedule-tasks": {
      "post": {
        "tags": [
          "Automation"
        ],
        "summary": "Schedule a Task on target endpoints",
        "operationId": "Schedule_Task",
        "security": [
          {
            "automation_create": [
              "platform.automation.create"
            ]
          }
        ]
      }
    },
    "/api/platform/api/platform/v1/automation/tasks/summary": {
      "get": {
        "tags": [
          "Automation"
        ],
        "summary": "Get Tasks Summary",
        "operationId": "Tasks_Summary",
        "security": [
          {
            "automation_read": [
              "platform.automation.read"
            ]
          }
        ]
      }
    },
    "/api/platform/v1/automation/endpoints/{endpointId}/tasks/summary": {
      "get": {
        "tags": [
          "Automation"
        ],
        "summary": "Get Tasks Summary for Endpoint",
        "operationId": "Endpoint_Task_Summary",
        "security": [
          {
            "automation_read": [
              "platform.automation.read"
            ]
          }
        ]
      }
    },
    "/api/platform/v1/automation/tasks/{taskId}/instance/summary": {
      "get": {
        "tags": [
          "Automation"
        ],
        "summary": "Get Task Instance Summary",
        "operationId": "Task_Instance_Summary",
        "security": [
          {
            "automation_read": [
              "platform.automation.read"
            ]
          }
        ]
      }
    },
    "/api/platform/v1/automation/tasks/{taskId}/instances/{instanceId}/results": {
      "get": {
        "tags": [
          "Automation"
        ],
        "summary": "Get Task Instance Execution Results",
        "operationId": "get_task_instance_execution_results",
        "security": [
          {
            "automation_read": [
              "platform.automation.read"
            ]
          }
        ]
      }
    },
    "/api/platform/v1/device/endpoints/{endpointId}/system-state-info": {
      "get": {
        "tags": [
          "Devices"
        ],
        "summary": "Get System State Information of Endpoint",
        "operationId": "System_State_Information_of_Endpoint",
        "security": [
          {
            "devices_read": [
              "platform.devices.read"
            ]
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "device_groups": {
        "type": "oauth2",
        "flows": {
          "clientCredentials": {
            "tokenUrl": "https://openapi.service.itsupport247.net/v1/token",
            "scopes": {
              "platform.deviceGroups.read": "read all automations"
            }
          }
        }
      },
      "automation_read": {
        "type": "oauth2",
        "flows": {
          "clientCredentials": {
            "tokenUrl": "https://openapi.service.itsupport247.net/v1/token",
            "scopes": {
              "platform.automation.read": "read all automations"
            }
          }
        }
      },
      "openapi_oauth": {
        "type": "oauth2",
        "flows": {
          "clientCredentials": {
            "tokenUrl": "https://openapi.service.itsupport247.net/v1/token",
            "scopes": {}
          }
        }
      },
      "topology": {
        "type": "oauth2",
        "flows": {
          "clientCredentials": {
            "tokenUrl": "https://openapi.service.itsupport247.net/v1/token",
            "scopes": {
              "topology": "read topology"
            }
          }
        }
      },
      "asset": {
        "type": "oauth2",
        "flows": {
          "clientCredentials": {
            "tokenUrl": "https://openapi.service.itsupport247.net/v1/token",
            "scopes": {
              "asset:all": "read all assets of the endpoint",
              "asset:baseboard": "read baseboard assets of the endpoint",
              "asset:bios": "read bios assets of the endpoint",
              "asset:drives": "read drives assets of the endpoint",
              "asset:networks": "read networks assets of the endpoint",
              "asset:os": "read os assets of the endpoint",
              "asset:system": "read system assets of the endpoint",
              "asset:software": "read software assets of the endpoint",
              "asset:users": "read users assets of the endpoint",
              "asset:services": "read services assets of the endpoint",
              "asset:shares": "read shares assets of the endpoint"
            }
          }
        }
      },
      "extended_attributes": {
        "type": "oauth2",
        "flows": {
          "clientCredentials": {
            "tokenUrl": "https://openapi.service.itsupport247.net/v1/token",
            "scopes": {
              "extended_attributes": "extended attributes management"
            }
          }
        }
      },
      "alerts": {
        "type": "oauth2",
        "flows": {
          "clientCredentials": {
            "tokenUrl": "https://openapi.service.itsupport247.net/v1/token",
            "scopes": {
              "alerts": "alerts management"
            }
          }
        }
      },
      "site_mapping": {
        "type": "oauth2",
        "flows": {
          "clientCredentials": {
            "tokenUrl": "https://openapi.service.itsupport247.net/v1/token",
            "scopes": {
              "site_mapping": "read site mappings"
            }
          }
        }
      },
      "endpoint_mapping": {
        "type": "oauth2",
        "flows": {
          "clientCredentials": {
            "tokenUrl": "https://openapi.service.itsupport247.net/v1/token",
            "scopes": {
              "endpoint_mapping": "endpoint mapping management"
            }
          }
        }
      },
      "network_and_monitoring": {
        "type": "oauth2",
        "flows": {
          "clientCredentials": {
            "tokenUrl": "https://openapi.service.itsupport247.net/v1/token",
            "scopes": {
              "network_and_monitoring": "network monitoring management"
            }
          }
        }
      },
      "platform": {
        "type": "oauth2",
        "flows": {
          "clientCredentials": {
            "tokenUrl": "https://openapi.service.itsupport247.net/v1/token",
            "scopes": {
              "platform.companies.read": "read all companies",
              "platform.sites.read": "read all sites",
              "platform.sites.write": "write all sites"
            }
          }
        }
      },
      "backupdashboard": {
        "type": "oauth2",
        "flows": {
          "clientCredentials": {
            "tokenUrl": "https://openapi.service.itsupport247.net/v1/token",
            "scopes": {
              "backupdashboard:create": "create backupdashboard"
            }
          }
        }
      },
      "endpoints_list": {
        "type": "oauth2",
        "flows": {
          "clientCredentials": {
            "tokenUrl": "https://openapi.service.itsupport247.net/v1/token",
            "scopes": {
              "platform.asset.read": "read all devices"
            }
          }
        }
      },
      "custom_fields": {
        "type": "oauth2",
        "flows": {
          "clientCredentials": {
            "tokenUrl": "https://openapi.service.itsupport247.net/v1/token",
            "scopes": {
              "platform.custom_fields_definitions.read": "View Custom Fields Definitions",
              "platform.custom_fields_definitions.write": "Update Custom Fields Definitions",
              "platform.custom_fields_values.read": "View Custom Fields Values",
              "platform.custom_fields_values.write": "Update Custom Fields Values"
            }
          }
        }
      },
      "automation_create": {
        "type": "oauth2",
        "flows": {
          "clientCredentials": {
            "tokenUrl": "https://openapi.service.itsupport247.net/v1/token",
            "scopes": {
              "platform.automation.create": "create automations"
            }
          }
        }
      },
      "devices_read": {
        "type": "oauth2",
        "flows": {
          "clientCredentials": {
            "tokenUrl": "https://openapi.service.itsupport247.net/v1/token",
            "scopes": {
              "platform.devices.read": "read all systemstates"
            }
          }
        }
      }
    }
  },
  "tags": [
    {
      "name": "Authorization"
    },
    {
      "name": "Rate Limits"
    },
    {
      "name": "Devices"
    },
    {
      "name": "Tickets"
    },
    {
      "name": "Custom Fields Values"
    },
    {
      "name": "Custom Fields Definitions"
    }
  ]
}